### PR TITLE
Adding/removing flyctl commands

### PR DESCRIPTION
**Pull request by monroeclinton**
Some commands were not listed on the sidebar so I added them. I removed the `flyctl builds` from documentation. I added a page for `flyctl curl` and `flyctl config env`. I removed non-existent commands from the postgres page

### CODE REVIEW

**Comment by tqbf** [comment]
Do we want to keep `flyctl curl`?

**Comment by mrkurt** [comment]
We do not want to keep `fly curl`!

**Comment by monroeclinton** [comment]
Removed curl

**Comment by jsierles** [comment]
Thanks for the hard work!

**Pull request merged**
