### PR TITLE
Add machines runtime env doc to machines nav and landing

### PR DESCRIPTION
**Pull request by andie787**
### Summary of changes

Add the new Machines runtime environment doc to the Machines nav and landing page.

@catflydotio I think this belongs in reference in the nav. And the way the landing page is now, I thought it best under Learn along with the machines state reference. Feel free to suggest changes!

### Related Fly.io community and GitHub links
#1385

### CODE REVIEW

**Comment by catflydotio** [comment]
Good catch, forgot about the subnav. Are we using sentence case or title case?

**Comment by andie787** [comment]
@catflydotio good question! Obviously we decided on sentence case for headings. And it looks like I've been doing that in the nav too :). What is your preference for the nav?

**Comment by catflydotio** [comment]
Whatever we have more of right now, ha!

**Comment by andie787** [comment]
Made the Machines nav items sentence case! Left the main nav alone for now.

**Pull request merged**
