### PR TITLE
Update flyctl_ssh_console.md

### PR DESCRIPTION
**Pull request by vyedin**
It's not super clear how to use this the first time to connect to an app, so I added a note to add the credential for the next person.

### CODE REVIEW

**Comment by catflydotio** [comment]
These docs have to be updated from their source in the flyctl repo or the next flyctl update will overwrite them.

**Comment by vyedin** [comment]
@catflydotio oh interesting. Do we want to take away the github link at the bottom then?

**Comment by catflydotio** [comment]
@vyedin Right now flyctl command docs use the docs template -- it's fine for all other docs and rarely does anyone try to edit one. So I'm not opposed but not sure it's a big deal either.

**Comment by catflydotio** [comment]
Actually it might be really easy to change on flyctl docs. Let me have a look

**Comment by catflydotio** [comment]
How's it look now? (https://github.com/superfly/docs/commit/a34e0fd98b07921de28cc65debf51f561d1bdf16)

**Pull request closed without merging**
